# example netlify.toml
[build]
  command = "cd packages/frontend && yarn build"
  functions = "lambdas"
  publish = "packages/frontend/public/"

[[headers]]
  for = "/app.css"
  [headers.values]
    Access-Control-Allow-Origin = "*"
